### ISSUE TITLE
Java heap space error with big for loop.

### ISSUE THREAD

**Issue by OmegaMetor** [Lemon-Chad/jpizza#5]
Error:
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at lemon.jpizza.Generators.Interpreter.visit_ForNode(Interpreter.java:292)
	at lemon.jpizza.Generators.Interpreter.visit(Interpreter.java:138)
	at lemon.jpizza.Generators.Interpreter.visit_ListNode(Interpreter.java:224)
	at lemon.jpizza.Generators.Interpreter.visit(Interpreter.java:149)
	at lemon.jpizza.Shell.run(Shell.java:295)
	at lemon.jpizza.Shell.run(Shell.java:286)
	at lemon.jpizza.Shell.main(Shell.java:164)`

Code:
`for (i -> 0:1000000000) => println(i);`

Explanation:
When trying to create a for loop with a massive amount of iterations, the interpreter dies before running any part of the loop. This may be dependent on the amount of ram the system has, so you might need to tweak the number to reproduce. This worked on a 2020 macbook air with 8gb of ram.

**Comment by Lemon-Chad** [comment]
Error is caught and resolved in JPizza RTError. Cannot really be fixed, as is due to running out of memory.
